# This file controls the settings for your Quarto template


# website settings
website:
  title: "GeoBridge"                               
  search: false
  site-url: https://geobridge.github.io
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: img/favicon.png
    
    # your sub-pages
    left:
      - href: seminars.qmd
        text: Monthly Seminar Series
      - href: uavworkshop.qmd
        text: UAV and RS Workshop
    

# Don't touch unless you know what you are doing :) ------------
  page-footer: 
    left: |
      <div id="fixed-copyright">Â© 2025 Augusto Lima & Sjur Barndon</div>
    right: |
      <span class="faux-block">
        <a href="https://www.uva.nl/en">
          <img src="img/uva.jpg" alt="left Logo" style="height: 40px; vertical-align: middle;">
        </a>
        <a href="https://www.uib.no/en">
          <img src="img/uib.png" alt="center Logo" style="height: 40px; vertical-align: middle;">
        </a>
        <a href="https://mohnfoundation.no/en/">
          <img src="img/trond.jpg" alt="right Logo" style="height: 40px; vertical-align: middle;">
        </a>
        <a href="https://bjerknes.uib.no/en">
          <img src="img/bjerknes.webp" alt="last Logo" style="height: 40px; vertical-align: middle;">
        </a>
      </span>

project:
  type: website
  output-dir: docs

  preview:
    browser: true
    watch-inputs: true
    navigate: true

format:
  html:
    fontsize: 1.3em
    theme: 
      - pulse
      - styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true